### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gambitcomminc**
added AWS IoT Get Started lab

# What is this workshop about

Hands-on "Get Started" lab for AWS IoT. Publish telemetry to AWS IoT core in minutes, not hours or days. 

## Describe the services involved

AWS IoT Lab on AWS Marketplace. Interacts with

AWS IoT Core

Investigate telemetry to AWS Cloudwatch, AWS DynamoDB, AWS IoT Rules, Lambdas, SNS, etc.

## What is the category

IoT

--

Anyone who agrees with this pull request could submit an :+1: for the owners to review.

### CODE REVIEW

**Comment by gambitcomminc** [comment]
Get started with AWS IoT in minutes, not hours or days.

**Comment by dgomesbr** [comment]
Hello @gambitcomminc! Thanks for the contribution, do you mind filling the the blanks so people can vote it for it and also I can understand all the aspects of the workshop.

Do you mind let me know if the workshop contains instructions for cleaning up at the end as well?

**Comment by gambitcomminc** [comment]
Done, I hope so.

**Comment by gambitcomminc** [comment]
Yes, of course any lab needs to clean up after itself. The lab has ALL instructions for FREE and PUBLIC. https://mqttlab.iotsim.io/aws has EVERYTHING.

**Pull request closed without merging**
